USE CUST_DB
ALTER DATABASE CUST_DB
ADD FILE (NAME = Cust_DB1, FLLENAME = 'C:\ProgramFIles\Microsoft SQL Server\
MSSQL11.MSSQLSERVER\MSSQL\DATA\Cust_DB1.ndf')
TO FLLEGROUP FG_ReadOnly
MODIEY FLLEGROUP FG_ReadOnly DEFAULT