CREATE DATABASE [salesDB] ON PRIMARY
(NAME = 'salesDB', FILLENAME ='C:\Program Files\Microsoft SQL Server\MSSQL11.
MSSQLSERVER\MSSQL\DATA\SalesDB.msf',SIZE=3072KB, MAXSIZE=UNLIMTED,
FLLEGOWTH=1024KB),
FLLEGROUP [MyFileGroup]
(NAME ='SalesDB_FG',FLLENAME='C:\ProgramFiles\Microsoft SQL Server\MSSQL11.
MSSQLSERVER\MSSQL\DATA\Sales_DB_FG.ndf',SIZE=3072KB, MAXSIZE=UNLIMITED,FLLEGROWTH=1024KB)